---
title: "Plot and validate CMIP6 downloads"
output: 
  html_document:
    toc: yes
    toc_float: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(pointblank)
library(tidyverse)
library(here)
library(patchwork)
library(lubridate)
library(tsibble)
library(units)
library(ggforce) #to get ggplot to work with `units`
library(gt)
theme_set(theme_bw())
# Use `validate_rmd()` here to set options for the
# pointblank validation workflow within R Markdown documents
```

```{r load_index, message=FALSE, warning=FALSE, include=FALSE}
idx <- read_csv(here("metadata", "cmip6_index.csv"))
```

# Check that all models were downloaded

Check that all the directories for the .nc files got made

```{r validate=TRUE}
source_dl <- dir(here("data_raw", "CMIP6"))
source_id <- idx$source_id %>% unique() %>% str_to_lower() %>% str_replace_all("-", "_")
stop_if_not(!any(!source_id %in% source_dl))
```

Check that all the corresponding .csv files exist

```{r validate=TRUE}
csvs <- list.files(here('data'))
stop_if_not(!any(!paste0(source_id, "_data.csv") %in% csvs))
```


```{r read_files, message=FALSE, warning=FALSE, include=FALSE}
#read in all files
df_list <-
  map(list.files(here('data'),
                 pattern = "data\\.csv$",
                 full.names = TRUE),
      read_csv) %>%
  set_names(map(., ~.x$source_id[1]))
```

```{r convert, include=FALSE}
water_density <- as_units(1000, "kg m-3")
convert_units <- function(x) {
  x  %>% 
    #set units
    mutate(across(c(hfls ,hfss), ~set_units(.x, "W m-2")),
           across(starts_with("tas"), ~set_units(.x, "K")),
           pr = set_units(pr, "kg m-2 s-1")) %>% 
    #do unit conversions
    mutate(across(starts_with("tas"), ~set_units(.x, "degC")),
           d_per_mon = days_in_month(month(time)) %>% set_units("d/month"), 
           pr = set_units((pr/water_density), "mm/d") * d_per_mon) %>% 
    select(-d_per_mon)
}
df_list <- map(df_list, convert_units)
```


```{r plot_fun, include=FALSE}
# Function to plot data
plot_all <- function(data) {
  p_list <- map(c("tas", "tasmin", "tasmax", "pr", "hfls", "hfss"),
      ~ggplot(data,
              aes_string(x = "time", y = .x, color = "experiment_id")) +
        geom_line(alpha = 0.5) + 
        geom_smooth(se = FALSE)
  ) 
  patchwork::wrap_plots(p_list, guides = "collect") &
    plot_annotation(title = data$source_id[1])
}
```



```{r include=FALSE}
xa_raw <- read_csv(here("data", "xavier_aggregated.csv"))
xa <- 
  xa_raw %>%
  mutate(date = paste(yearmonth, 1) %>% ymd(),
         month = month(date, label = TRUE)) %>% 
  group_by(month) %>%
  summarize(across(c(pr, starts_with("tas")), mean)) %>%
  mutate(pr = set_units(pr, "mm/month"),
         across(starts_with("tas"), ~set_units(.x, "degC")))
```



# Seasonality

```{r include=FALSE}
season_df <- 
  df_list %>% 
  map_dfr(~{.x %>% 
    filter(time >= ymd("1980-01-01") &
             time <= ymd("2015-09-30")) %>% 
      mutate(month = month(time), .after=time) %>% 
      group_by(month) %>% 
      summarize(across(c(pr, tas, tasmin, tasmax), mean,
                       .names = "mean_{.col}")) 
  }, .id = "source_id")
```


```{r include=FALSE}
xa2 <- xa %>% 
  rename_with(~paste0("mean_", .), .cols = -month) %>% 
  add_column(source_id = "Observed") %>% 
  mutate(month = as.numeric(month))
season_df <- bind_rows(xa2, season_df) %>% 
  #move "observed" to the top by making it the first level
  mutate(source_id = fct_inorder(source_id))
```

```{r include=FALSE}
# Create mini plots of monthly average precip and temperature for table

# season_df$mean_pr %>% range()
# season_df$mean_tasmin %>% min()
# season_df$mean_tasmax %>% max()

plots <-
  season_df %>%  
  group_by(source_id) %>%
  nest() %>% 
  mutate(
    pr_season = map(data, ~{
      ggplot(.x, aes(x = month, y = mean_pr)) +
        geom_col(fill = "blue") +
        scale_x_continuous("", breaks = 1:12,
                           labels = ~month(.x, label = FALSE)) +
        scale_y_unit("pr", limits = c(0, 456)) +
        theme(text = element_text(size = 35))
    }),
    tas_season = map(data, ~{
      ggplot(.x, aes(x = month)) +
        geom_ribbon(aes(ymin = mean_tasmin, ymax = mean_tasmax),
                    fill = "red",
                    alpha = 0.5) +
        geom_line(aes(y = mean_tas), color = "red") +
        scale_x_continuous("",
                           breaks = 1:12,
                           labels = ~ month(.x, label = FALSE)) +
        scale_y_unit("tas", limits = c(19, 43)) +
        theme(text = element_text(size = 35))
    })) %>% 
      select(-data)
```




```{r include=FALSE}
table_rough <-
  season_df %>%
  group_by(source_id) %>%
  summarize(pr_cor = cor(mean_pr, xa$pr),
            tas_cor = cor(mean_tas, xa$tas),
            tasmin_cor = cor(mean_tasmin, xa$tasmin),
            tasmax_cor = cor(mean_tasmax, xa$tasmax)) %>%
  #make columns for plots to go eventually
  mutate(pr_plot = NA) %>%
  mutate(tas_plot = NA) %>% 
  #make into gt
  gt() %>%
  #place plots
  text_transform(
    locations = cells_body(pr_plot),
    fn = function(x) {
      map(plots$pr_season,
          ggplot_image,
          height = px(80),
          aspect_ratio = 1.5)
    }
  ) %>% 
  text_transform(
    locations = cells_body(tas_plot),
    fn = function(x) {
      map(plots$tas_season,
          ggplot_image,
          height = px(80),
          aspect_ratio = 1.5)
    }
  ) %>% 
  # round correlations
  fmt_number(ends_with("_cor")) 
```

```{r echo=FALSE}
table_rough %>% 
  # highlight poor correlations
  tab_style(
    style = list(
      cell_text(color = "red")
    ),
    locations = cells_body(
      columns = pr_cor,
      rows = pr_cor < 0.5
    )
  ) %>% 
    tab_style(
    style = list(
      cell_text(color = "red")
    ),
    locations = cells_body(
      columns = tas_cor,
      rows = tas_cor < 0.5
    )
  )  %>% 
  tab_style(
    style = list(
      cell_text(color = "red")
    ),
    locations = cells_body(
      columns = tasmin_cor,
      rows = tasmin_cor < 0.5
    )
  ) %>% 
    tab_style(
    style = list(
      cell_text(color = "red")
    ),
    locations = cells_body(
      columns = tasmax_cor,
      rows = tasmax_cor < 0.5
    )
  ) %>% 
  tab_spanner("Correlation to observed", ends_with("cor")) %>% 
  tab_spanner("Seasonality", ends_with("_plot")) %>% 
  cols_label(
    source_id = "Source",
    pr_cor = "pr",
    tas_cor = "tas",
    tasmin_cor = "tasmin",
    tasmax_cor = "tasmax",
    pr_plot = "precipitation",
    tas_plot = "temperature"
  ) %>% 
  tab_source_note(
    source_note = md(
      "Observed data from [Xavier et al. (2016)](https://doi.org/10.1002/joc.4518)")
  )
```


# CMIP model details

Below are validation reports and plots of all data downloaded from each CMIP6 source.

```{r echo=FALSE}
i=1
htmltools::h2(names(df_list[i]))
```
```{r validate=TRUE}
  col_exists(
    df_list[[i]],
    c("hfls", "hfss", "tas", "tasmin", "tasmax", "pr"),
    label = "all variables exist"
    ) 
  col_vals_make_set(
    df_list[[i]],
    experiment_id,
    c("historical", "ssp126", "ssp245", "ssp585"),
    label = "all scenarios exist"
  )
  col_vals_not_null(
    df_list[[i]],
    vars(hfls, hfss, tas, tasmin, tasmax, pr),
    label = "no missing values"
  )
  col_vals_expr(df_list[[i]], ~max(.$pr) > as_units(200, "mm/month"))
  col_is_posix(df_list[[i]], time)
  col_vals_between(
    df_list[[i]],
    time,
    ymd_hms("1850-01-01 12:00:00"),
    ymd_hms("2014-12-31 12:00:00"),
    preconditions = ~ . %>% filter(experiment_id == "historical"),
    label = "full time series"
  )
  col_vals_between(
    df_list[[i]],
    time,
    ymd_hms("2015-01-01 12:00:00"),
    ymd_hms("2100-12-31 12:00:00"),
    preconditions = ~ . %>% filter(experiment_id != "historical"),
    label = "full time series"
  )
```
```{r echo=FALSE, message=FALSE, warning=FALSE}
plot_all(df_list[[i]])
```



```{r echo=FALSE}
i=2
htmltools::h2(names(df_list[i]))
```
```{r validate=TRUE}
  col_exists(
    df_list[[i]],
    c("hfls", "hfss", "tas", "tasmin", "tasmax", "pr"),
    label = "all variables exist"
    ) 
  col_vals_make_set(
    df_list[[i]],
    experiment_id,
    c("historical", "ssp126", "ssp245", "ssp585"),
    label = "all scenarios exist"
  )
  col_vals_not_null(
    df_list[[i]],
    vars(hfls, hfss, tas, tasmin, tasmax, pr),
    label = "no missing values"
  )
  col_vals_expr(df_list[[i]], ~max(.$pr) > as_units(200, "mm/month"))
  col_is_posix(df_list[[i]], time)
  col_vals_between(
    df_list[[i]],
    time,
    ymd_hms("1850-01-01 12:00:00"),
    ymd_hms("2014-12-31 12:00:00"),
    preconditions = ~ . %>% filter(experiment_id == "historical"),
    label = "full time series"
  )
  col_vals_between(
    df_list[[i]],
    time,
    ymd_hms("2015-01-01 12:00:00"),
    ymd_hms("2100-12-31 12:00:00"),
    preconditions = ~ . %>% filter(experiment_id != "historical"),
    label = "full time series"
  )
```
```{r echo=FALSE, message=FALSE, warning=FALSE}
plot_all(df_list[[i]])
```


```{r echo=FALSE}
i=3
htmltools::h2(names(df_list[i]))
```
```{r validate=TRUE}
  col_exists(
    df_list[[i]],
    c("hfls", "hfss", "tas", "tasmin", "tasmax", "pr"),
    label = "all variables exist"
    ) 
  col_vals_make_set(
    df_list[[i]],
    experiment_id,
    c("historical", "ssp126", "ssp245", "ssp585"),
    label = "all scenarios exist"
  )
  col_vals_not_null(
    df_list[[i]],
    vars(hfls, hfss, tas, tasmin, tasmax, pr),
    label = "no missing values"
  )
  col_vals_expr(df_list[[i]], ~max(.$pr) > as_units(200, "mm/month"))
  col_is_posix(df_list[[i]], time)
  col_vals_between(
    df_list[[i]],
    time,
    ymd_hms("1850-01-01 12:00:00"),
    ymd_hms("2014-12-31 12:00:00"),
    preconditions = ~ . %>% filter(experiment_id == "historical"),
    label = "full time series"
  )
  col_vals_between(
    df_list[[i]],
    time,
    ymd_hms("2015-01-01 12:00:00"),
    ymd_hms("2100-12-31 12:00:00"),
    preconditions = ~ . %>% filter(experiment_id != "historical"),
    label = "full time series"
  )
```
```{r echo=FALSE, message=FALSE, warning=FALSE}
plot_all(df_list[[i]])
```


```{r echo=FALSE}
i=4
htmltools::h2(names(df_list[i]))
```
```{r validate=TRUE}
  col_exists(
    df_list[[i]],
    c("hfls", "hfss", "tas", "tasmin", "tasmax", "pr"),
    label = "all variables exist"
    ) 
  col_vals_make_set(
    df_list[[i]],
    experiment_id,
    c("historical", "ssp126", "ssp245", "ssp585"),
    label = "all scenarios exist"
  )
  col_vals_not_null(
    df_list[[i]],
    vars(hfls, hfss, tas, tasmin, tasmax, pr),
    label = "no missing values"
  )
  col_vals_expr(df_list[[i]], ~max(.$pr) > as_units(200, "mm/month"))
  col_is_posix(df_list[[i]], time)
  col_vals_between(
    df_list[[i]],
    time,
    ymd_hms("1850-01-01 12:00:00"),
    ymd_hms("2014-12-31 12:00:00"),
    preconditions = ~ . %>% filter(experiment_id == "historical"),
    label = "full time series"
  )
  col_vals_between(
    df_list[[i]],
    time,
    ymd_hms("2015-01-01 12:00:00"),
    ymd_hms("2100-12-31 12:00:00"),
    preconditions = ~ . %>% filter(experiment_id != "historical"),
    label = "full time series"
  )
```
```{r echo=FALSE, message=FALSE, warning=FALSE}
plot_all(df_list[[i]])
```


```{r echo=FALSE}
i=5
htmltools::h2(names(df_list[i]))
```
```{r validate=TRUE}
  col_exists(
    df_list[[i]],
    c("hfls", "hfss", "tas", "tasmin", "tasmax", "pr"),
    label = "all variables exist"
    ) 
  col_vals_make_set(
    df_list[[i]],
    experiment_id,
    c("historical", "ssp126", "ssp245", "ssp585"),
    label = "all scenarios exist"
  )
  col_vals_not_null(
    df_list[[i]],
    vars(hfls, hfss, tas, tasmin, tasmax, pr),
    label = "no missing values"
  )
  col_vals_expr(df_list[[i]], ~max(.$pr) > as_units(200, "mm/month"))
  col_is_posix(df_list[[i]], time)
  col_vals_between(
    df_list[[i]],
    time,
    ymd_hms("1850-01-01 12:00:00"),
    ymd_hms("2014-12-31 12:00:00"),
    preconditions = ~ . %>% filter(experiment_id == "historical"),
    label = "full time series"
  )
  col_vals_between(
    df_list[[i]],
    time,
    ymd_hms("2015-01-01 12:00:00"),
    ymd_hms("2100-12-31 12:00:00"),
    preconditions = ~ . %>% filter(experiment_id != "historical"),
    label = "full time series"
  )
```
```{r echo=FALSE, message=FALSE, warning=FALSE}
plot_all(df_list[[i]])
```


```{r echo=FALSE}
i=6
htmltools::h2(names(df_list[i]))
```
```{r validate=TRUE}
  col_exists(
    df_list[[i]],
    c("hfls", "hfss", "tas", "tasmin", "tasmax", "pr"),
    label = "all variables exist"
    ) 
  col_vals_make_set(
    df_list[[i]],
    experiment_id,
    c("historical", "ssp126", "ssp245", "ssp585"),
    label = "all scenarios exist"
  )
  col_vals_not_null(
    df_list[[i]],
    vars(hfls, hfss, tas, tasmin, tasmax, pr),
    label = "no missing values"
  )
  col_vals_expr(df_list[[i]], ~max(.$pr) > as_units(200, "mm/month"))
  col_is_posix(df_list[[i]], time)
  col_vals_between(
    df_list[[i]],
    time,
    ymd_hms("1850-01-01 12:00:00"),
    ymd_hms("2014-12-31 12:00:00"),
    preconditions = ~ . %>% filter(experiment_id == "historical"),
    label = "full time series"
  )
  col_vals_between(
    df_list[[i]],
    time,
    ymd_hms("2015-01-01 12:00:00"),
    ymd_hms("2100-12-31 12:00:00"),
    preconditions = ~ . %>% filter(experiment_id != "historical"),
    label = "full time series"
  )
```
```{r echo=FALSE, message=FALSE, warning=FALSE}
plot_all(df_list[[i]])
```


```{r echo=FALSE}
i=7
htmltools::h2(names(df_list[i]))
```
```{r validate=TRUE}
  col_exists(
    df_list[[i]],
    c("hfls", "hfss", "tas", "tasmin", "tasmax", "pr"),
    label = "all variables exist"
    ) 
  col_vals_make_set(
    df_list[[i]],
    experiment_id,
    c("historical", "ssp126", "ssp245", "ssp585"),
    label = "all scenarios exist"
  )
  col_vals_not_null(
    df_list[[i]],
    vars(hfls, hfss, tas, tasmin, tasmax, pr),
    label = "no missing values"
  )
  col_vals_expr(df_list[[i]], ~max(.$pr) > as_units(200, "mm/month"))
  col_is_posix(df_list[[i]], time)
  col_vals_between(
    df_list[[i]],
    time,
    ymd_hms("1850-01-01 12:00:00"),
    ymd_hms("2014-12-31 12:00:00"),
    preconditions = ~ . %>% filter(experiment_id == "historical"),
    label = "full time series"
  )
  col_vals_between(
    df_list[[i]],
    time,
    ymd_hms("2015-01-01 12:00:00"),
    ymd_hms("2100-12-31 12:00:00"),
    preconditions = ~ . %>% filter(experiment_id != "historical"),
    label = "full time series"
  )
```
```{r echo=FALSE, message=FALSE, warning=FALSE}
plot_all(df_list[[i]])
```


```{r echo=FALSE}
i=8
htmltools::h2(names(df_list[i]))
```
```{r validate=TRUE}
  col_exists(
    df_list[[i]],
    c("hfls", "hfss", "tas", "tasmin", "tasmax", "pr"),
    label = "all variables exist"
    ) 
  col_vals_make_set(
    df_list[[i]],
    experiment_id,
    c("historical", "ssp126", "ssp245", "ssp585"),
    label = "all scenarios exist"
  )
  col_vals_not_null(
    df_list[[i]],
    vars(hfls, hfss, tas, tasmin, tasmax, pr),
    label = "no missing values"
  )
  col_vals_expr(df_list[[i]], ~max(.$pr) > as_units(200, "mm/month"))
  col_is_posix(df_list[[i]], time)
  col_vals_between(
    df_list[[i]],
    time,
    ymd_hms("1850-01-01 12:00:00"),
    ymd_hms("2014-12-31 12:00:00"),
    preconditions = ~ . %>% filter(experiment_id == "historical"),
    label = "full time series"
  )
  col_vals_between(
    df_list[[i]],
    time,
    ymd_hms("2015-01-01 12:00:00"),
    ymd_hms("2100-12-31 12:00:00"),
    preconditions = ~ . %>% filter(experiment_id != "historical"),
    label = "full time series"
  )
```
```{r echo=FALSE, message=FALSE, warning=FALSE}
plot_all(df_list[[i]])
```


```{r echo=FALSE}
i=9
htmltools::h2(names(df_list[i]))
```
```{r validate=TRUE}
  col_exists(
    df_list[[i]],
    c("hfls", "hfss", "tas", "tasmin", "tasmax", "pr"),
    label = "all variables exist"
    ) 
  col_vals_make_set(
    df_list[[i]],
    experiment_id,
    c("historical", "ssp126", "ssp245", "ssp585"),
    label = "all scenarios exist"
  )
  col_vals_not_null(
    df_list[[i]],
    vars(hfls, hfss, tas, tasmin, tasmax, pr),
    label = "no missing values"
  )
  col_vals_expr(df_list[[i]], ~max(.$pr) > as_units(200, "mm/month"))
  col_is_posix(df_list[[i]], time)
  col_vals_between(
    df_list[[i]],
    time,
    ymd_hms("1850-01-01 12:00:00"),
    ymd_hms("2014-12-31 12:00:00"),
    preconditions = ~ . %>% filter(experiment_id == "historical"),
    label = "full time series"
  )
  col_vals_between(
    df_list[[i]],
    time,
    ymd_hms("2015-01-01 12:00:00"),
    ymd_hms("2100-12-31 12:00:00"),
    preconditions = ~ . %>% filter(experiment_id != "historical"),
    label = "full time series"
  )
```
```{r echo=FALSE, message=FALSE, warning=FALSE}
plot_all(df_list[[i]])
```


```{r echo=FALSE}
i=10
htmltools::h2(names(df_list[i]))
```
```{r validate=TRUE}
  col_exists(
    df_list[[i]],
    c("hfls", "hfss", "tas", "tasmin", "tasmax", "pr"),
    label = "all variables exist"
    ) 
  col_vals_make_set(
    df_list[[i]],
    experiment_id,
    c("historical", "ssp126", "ssp245", "ssp585"),
    label = "all scenarios exist"
  )
  col_vals_not_null(
    df_list[[i]],
    vars(hfls, hfss, tas, tasmin, tasmax, pr),
    label = "no missing values"
  )
  col_vals_expr(df_list[[i]], ~max(.$pr) > as_units(200, "mm/month"))
  col_is_posix(df_list[[i]], time)
  col_vals_between(
    df_list[[i]],
    time,
    ymd_hms("1850-01-01 12:00:00"),
    ymd_hms("2014-12-31 12:00:00"),
    preconditions = ~ . %>% filter(experiment_id == "historical"),
    label = "full time series"
  )
  col_vals_between(
    df_list[[i]],
    time,
    ymd_hms("2015-01-01 12:00:00"),
    ymd_hms("2100-12-31 12:00:00"),
    preconditions = ~ . %>% filter(experiment_id != "historical"),
    label = "full time series"
  )
```
```{r echo=FALSE, message=FALSE, warning=FALSE}
plot_all(df_list[[i]])
```


```{r echo=FALSE}
i=11
htmltools::h2(names(df_list[i]))
```
```{r validate=TRUE}
  col_exists(
    df_list[[i]],
    c("hfls", "hfss", "tas", "tasmin", "tasmax", "pr"),
    label = "all variables exist"
    ) 
  col_vals_make_set(
    df_list[[i]],
    experiment_id,
    c("historical", "ssp126", "ssp245", "ssp585"),
    label = "all scenarios exist"
  )
  col_vals_not_null(
    df_list[[i]],
    vars(hfls, hfss, tas, tasmin, tasmax, pr),
    label = "no missing values"
  )
  col_vals_expr(df_list[[i]], ~max(.$pr) > as_units(200, "mm/month"))
  col_is_posix(df_list[[i]], time)
  col_vals_between(
    df_list[[i]],
    time,
    ymd_hms("1850-01-01 12:00:00"),
    ymd_hms("2014-12-31 12:00:00"),
    preconditions = ~ . %>% filter(experiment_id == "historical"),
    label = "full time series"
  )
  col_vals_between(
    df_list[[i]],
    time,
    ymd_hms("2015-01-01 12:00:00"),
    ymd_hms("2100-12-31 12:00:00"),
    preconditions = ~ . %>% filter(experiment_id != "historical"),
    label = "full time series"
  )
```
```{r echo=FALSE, message=FALSE, warning=FALSE}
plot_all(df_list[[i]])
```


```{r echo=FALSE}
i=12
htmltools::h2(names(df_list[i]))
```
```{r validate=TRUE}
  col_exists(
    df_list[[i]],
    c("hfls", "hfss", "tas", "tasmin", "tasmax", "pr"),
    label = "all variables exist"
    ) 
  col_vals_make_set(
    df_list[[i]],
    experiment_id,
    c("historical", "ssp126", "ssp245", "ssp585"),
    label = "all scenarios exist"
  )
  col_vals_not_null(
    df_list[[i]],
    vars(hfls, hfss, tas, tasmin, tasmax, pr),
    label = "no missing values"
  )
  col_vals_expr(df_list[[i]], ~max(.$pr) > as_units(200, "mm/month"))
  col_is_posix(df_list[[i]], time)
  col_vals_between(
    df_list[[i]],
    time,
    ymd_hms("1850-01-01 12:00:00"),
    ymd_hms("2014-12-31 12:00:00"),
    preconditions = ~ . %>% filter(experiment_id == "historical"),
    label = "full time series"
  )
  col_vals_between(
    df_list[[i]],
    time,
    ymd_hms("2015-01-01 12:00:00"),
    ymd_hms("2100-12-31 12:00:00"),
    preconditions = ~ . %>% filter(experiment_id != "historical"),
    label = "full time series"
  )
```
```{r echo=FALSE, message=FALSE, warning=FALSE}
plot_all(df_list[[i]])
```


```{r echo=FALSE}
i=13
htmltools::h2(names(df_list[i]))
```
```{r validate=TRUE}
  col_exists(
    df_list[[i]],
    c("hfls", "hfss", "tas", "tasmin", "tasmax", "pr"),
    label = "all variables exist"
    ) 
  col_vals_make_set(
    df_list[[i]],
    experiment_id,
    c("historical", "ssp126", "ssp245", "ssp585"),
    label = "all scenarios exist"
  )
  col_vals_not_null(
    df_list[[i]],
    vars(hfls, hfss, tas, tasmin, tasmax, pr),
    label = "no missing values"
  )
  col_vals_expr(df_list[[i]], ~max(.$pr) > as_units(200, "mm/month"))
  col_is_posix(df_list[[i]], time)
  col_vals_between(
    df_list[[i]],
    time,
    ymd_hms("1850-01-01 12:00:00"),
    ymd_hms("2014-12-31 12:00:00"),
    preconditions = ~ . %>% filter(experiment_id == "historical"),
    label = "full time series"
  )
  col_vals_between(
    df_list[[i]],
    time,
    ymd_hms("2015-01-01 12:00:00"),
    ymd_hms("2100-12-31 12:00:00"),
    preconditions = ~ . %>% filter(experiment_id != "historical"),
    label = "full time series"
  )
```
```{r echo=FALSE, message=FALSE, warning=FALSE}
plot_all(df_list[[i]])
```


```{r echo=FALSE}
i=14
htmltools::h2(names(df_list[i]))
```
```{r validate=TRUE}
  col_exists(
    df_list[[i]],
    c("hfls", "hfss", "tas", "tasmin", "tasmax", "pr"),
    label = "all variables exist"
    ) 
  col_vals_make_set(
    df_list[[i]],
    experiment_id,
    c("historical", "ssp126", "ssp245", "ssp585"),
    label = "all scenarios exist"
  )
  col_vals_not_null(
    df_list[[i]],
    vars(hfls, hfss, tas, tasmin, tasmax, pr),
    label = "no missing values"
  )
  col_vals_expr(df_list[[i]], ~max(.$pr) > as_units(200, "mm/month"))
  col_is_posix(df_list[[i]], time)
  col_vals_between(
    df_list[[i]],
    time,
    ymd_hms("1850-01-01 12:00:00"),
    ymd_hms("2014-12-31 12:00:00"),
    preconditions = ~ . %>% filter(experiment_id == "historical"),
    label = "full time series"
  )
  col_vals_between(
    df_list[[i]],
    time,
    ymd_hms("2015-01-01 12:00:00"),
    ymd_hms("2100-12-31 12:00:00"),
    preconditions = ~ . %>% filter(experiment_id != "historical"),
    label = "full time series"
  )
```
```{r echo=FALSE, message=FALSE, warning=FALSE}
plot_all(df_list[[i]])
```


```{r echo=FALSE}
i=15
htmltools::h2(names(df_list[i]))
```
```{r validate=TRUE}
  col_exists(
    df_list[[i]],
    c("hfls", "hfss", "tas", "tasmin", "tasmax", "pr"),
    label = "all variables exist"
    ) 
  col_vals_make_set(
    df_list[[i]],
    experiment_id,
    c("historical", "ssp126", "ssp245", "ssp585"),
    label = "all scenarios exist"
  )
  col_vals_not_null(
    df_list[[i]],
    vars(hfls, hfss, tas, tasmin, tasmax, pr),
    label = "no missing values"
  )
  col_vals_expr(df_list[[i]], ~max(.$pr) > as_units(200, "mm/month"))
  col_is_posix(df_list[[i]], time)
  col_vals_between(
    df_list[[i]],
    time,
    ymd_hms("1850-01-01 12:00:00"),
    ymd_hms("2014-12-31 12:00:00"),
    preconditions = ~ . %>% filter(experiment_id == "historical"),
    label = "full time series"
  )
  col_vals_between(
    df_list[[i]],
    time,
    ymd_hms("2015-01-01 12:00:00"),
    ymd_hms("2100-12-31 12:00:00"),
    preconditions = ~ . %>% filter(experiment_id != "historical"),
    label = "full time series"
  )
```
```{r echo=FALSE, message=FALSE, warning=FALSE}
plot_all(df_list[[i]])
```


```{r echo=FALSE}
i=16
htmltools::h2(names(df_list[i]))
```
```{r validate=TRUE}
  col_exists(
    df_list[[i]],
    c("hfls", "hfss", "tas", "tasmin", "tasmax", "pr"),
    label = "all variables exist"
    ) 
  col_vals_make_set(
    df_list[[i]],
    experiment_id,
    c("historical", "ssp126", "ssp245", "ssp585"),
    label = "all scenarios exist"
  )
  col_vals_not_null(
    df_list[[i]],
    vars(hfls, hfss, tas, tasmin, tasmax, pr),
    label = "no missing values"
  )
  col_vals_expr(df_list[[i]], ~max(.$pr) > as_units(200, "mm/month"))
  col_is_posix(df_list[[i]], time)
  col_vals_between(
    df_list[[i]],
    time,
    ymd_hms("1850-01-01 12:00:00"),
    ymd_hms("2014-12-31 12:00:00"),
    preconditions = ~ . %>% filter(experiment_id == "historical"),
    label = "full time series"
  )
  col_vals_between(
    df_list[[i]],
    time,
    ymd_hms("2015-01-01 12:00:00"),
    ymd_hms("2100-12-31 12:00:00"),
    preconditions = ~ . %>% filter(experiment_id != "historical"),
    label = "full time series"
  )
```
```{r echo=FALSE, message=FALSE, warning=FALSE}
plot_all(df_list[[i]])
```



```{r echo=FALSE}
i=17
htmltools::h2(names(df_list[i]))
```
```{r validate=TRUE}
  col_exists(
    df_list[[i]],
    c("hfls", "hfss", "tas", "tasmin", "tasmax", "pr"),
    label = "all variables exist"
    ) 
  col_vals_make_set(
    df_list[[i]],
    experiment_id,
    c("historical", "ssp126", "ssp245", "ssp585"),
    label = "all scenarios exist"
  )
  col_vals_not_null(
    df_list[[i]],
    vars(hfls, hfss, tas, tasmin, tasmax, pr),
    label = "no missing values"
  )
  col_vals_expr(df_list[[i]], ~max(.$pr) > as_units(200, "mm/month"))
  col_is_posix(df_list[[i]], time)
  col_vals_between(
    df_list[[i]],
    time,
    ymd_hms("1850-01-01 12:00:00"),
    ymd_hms("2014-12-31 12:00:00"),
    preconditions = ~ . %>% filter(experiment_id == "historical"),
    label = "full time series"
  )
  col_vals_between(
    df_list[[i]],
    time,
    ymd_hms("2015-01-01 12:00:00"),
    ymd_hms("2100-12-31 12:00:00"),
    preconditions = ~ . %>% filter(experiment_id != "historical"),
    label = "full time series"
  )
```
```{r echo=FALSE, message=FALSE, warning=FALSE}
plot_all(df_list[[i]])
```



```{r echo=FALSE}
i=18
htmltools::h2(names(df_list[i]))
```
```{r validate=TRUE}
  col_exists(
    df_list[[i]],
    c("hfls", "hfss", "tas", "tasmin", "tasmax", "pr"),
    label = "all variables exist"
    ) 
  col_vals_make_set(
    df_list[[i]],
    experiment_id,
    c("historical", "ssp126", "ssp245", "ssp585"),
    label = "all scenarios exist"
  )
  col_vals_not_null(
    df_list[[i]],
    vars(hfls, hfss, tas, tasmin, tasmax, pr),
    label = "no missing values"
  )
  col_vals_expr(df_list[[i]], ~max(.$pr) > as_units(200, "mm/month"))
  col_is_posix(df_list[[i]], time)
  col_vals_between(
    df_list[[i]],
    time,
    ymd_hms("1850-01-01 12:00:00"),
    ymd_hms("2014-12-31 12:00:00"),
    preconditions = ~ . %>% filter(experiment_id == "historical"),
    label = "full time series"
  )
  col_vals_between(
    df_list[[i]],
    time,
    ymd_hms("2015-01-01 12:00:00"),
    ymd_hms("2100-12-31 12:00:00"),
    preconditions = ~ . %>% filter(experiment_id != "historical"),
    label = "full time series"
  )
```
```{r echo=FALSE, message=FALSE, warning=FALSE}
plot_all(df_list[[i]])
```



```{r echo=FALSE}
i=19
htmltools::h2(names(df_list[i]))
```
```{r validate=TRUE}
  col_exists(
    df_list[[i]],
    c("hfls", "hfss", "tas", "tasmin", "tasmax", "pr"),
    label = "all variables exist"
    ) 
  col_vals_make_set(
    df_list[[i]],
    experiment_id,
    c("historical", "ssp126", "ssp245", "ssp585"),
    label = "all scenarios exist"
  )
  col_vals_not_null(
    df_list[[i]],
    vars(hfls, hfss, tas, tasmin, tasmax, pr),
    label = "no missing values"
  )
  col_vals_expr(df_list[[i]], ~max(.$pr) > as_units(200, "mm/month"))
  col_is_posix(df_list[[i]], time)
  col_vals_between(
    df_list[[i]],
    time,
    ymd_hms("1850-01-01 12:00:00"),
    ymd_hms("2014-12-31 12:00:00"),
    preconditions = ~ . %>% filter(experiment_id == "historical"),
    label = "full time series"
  )
  col_vals_between(
    df_list[[i]],
    time,
    ymd_hms("2015-01-01 12:00:00"),
    ymd_hms("2100-12-31 12:00:00"),
    preconditions = ~ . %>% filter(experiment_id != "historical"),
    label = "full time series"
  )
```
```{r echo=FALSE, message=FALSE, warning=FALSE}
plot_all(df_list[[i]])
```


