---
title: "Using global climate model outputs for ecological experiments and forecasting at a local scale"
shorttitle: "Running Title"
author:
  - Eric R. Scott:
      email: scottericr@gmail.com
      institute: [UF_WEC]
      correspondence: true
  - Co-author two:
      email: secondperson@university.edu
      institute: [affiliation2]
      correspondence: false
  - Co-author three:
      email: thirdperson@university.edu
      institute: [UF_WEC, affiliation2]
      correspondence: false
institute:
  - UF_WEC: Department of Wildlife Ecology and Conservation, University of Florida, Gainesville, Florida 32611-0430
  - affiliation2: Department of Ecology, Evolution and Environmental Biology, Example University 123 Center Avenue, New York, New York 10027 USA
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
    bookdown::word_document2:
      linenumbers: yes
      number_sections: no
      fig_caption: yes
      reference_docx: "templates/template.docx" # Insert path for the DOCX file
      pandoc_args:
      - --lua-filter=templates/scholarly-metadata.lua
      - --lua-filter=templates/author-info-blocks.lua
      #- -Fpandoc-crossref #required for cross-ref equations
linkcolor: blue
bibliography: references.bib
csl: "templates/global-change-biology.csl" # Insert path for the bib-style
keywords: |
  keyword1; keyword2; keyword3
highlights: |
  These are the highlights
  
editor_options:
  markdown:
    wrap: sentence
    canonical: true
---

<!-- This is the format for text comments that will be ignored during renderings. Do not put R code in these comments because it will not be ignored. -->

<!-- With the following code you can access and display values from the yml header above. -->

Keywords: `r rmarkdown::metadata$keywords`

Running title: `r rmarkdown::metadata$shorttitle`

<!-- Highlights: `r rmarkdown::metadata$highlights` -->

<!-- The following code chunk defines some general settings how code chunks should behave. -->

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	fig.path = "figures/",
	dev = "png",
	dpi = 300,
	message = FALSE,
	warning = FALSE,
	collapse = TRUE,
	comment = "#>"
)
```

# Abstract

Abstract text

\pagebreak

# Introduction

1.  What are these climate models?
    General circulation models (GCMs) model the Earth's climate by modeling ocean, atmospheric, and land as coupled systems.
    [more].
    The Coupled Model Intercomparison Project (CMIP) provides specific starting conditions and "experiments" for these GCMs to run.
    CMIP is now in its 6th iteration, corresponding with the 6th report of the Intergovernmental Panel on Climate Change (IPCC).
    The "experiments" correspond to shared socioeconomic pathways (SSPs) laid out in the IPCC's 6th report.
    These SSPs differ from the representative concentration pathways (RCPs) used in the previous IPPC report and in CMIP5 models in that they consider a range of global socioeconomic possibilities ranging from very optimistic elimination of fossil fuel consumption and carbon capture technologies with strong international cooperation, to expansion of fascism and nationalism, continued investment in fossil fuel technologies, and increasing global inequality.
    These scenarios are then combined with "forcings" comparable to the RCPs of CMIP5.
    Four combinations of SSPs and radiative forcing levels were decided upon as standard across the model intercomparison project: SSP126, SSP245, SSP370, and SSP585.
    <!--# in box, explain that SSP126 is actually SSP1 (sustainable, reduced inequality) with a 2.6 Wm-1 forcing level -->.

    Something about spatial nature and resolution.
    Something about uncertainty [ecologists will think pixel-to-pixel variation is 'made up' (and maybe it is to some extent)].
    How to use uncertainty within and among models to your advantage?

2.  Why should ecologists be interested?
    Ecologists and global change biologists are often interested in the impacts of climate change on natural systems [cite some study about increase in climate change biology over time].

In manipulative experiments, researchers manipulate climatic variables to test the effects of future climate change through warming [@peterjohnResponsesTraceGas1994], drought [@scottInteractiveEffectsDrought2019], or rising CO2 [@mcleodFreeairCarbonDioxide1999], or some combination of variables [@hoeppnerInteractiveResponsesOldfield2012; @oriansCombinedImpactsProlonged2019] <!--# add citations probably, especially warming.  Add an arctic example with those plastic hexagon things -->.
The treatment levels used in these experimental studies are often round numbers representing rough approximations of future conditions (e.g. 50%, 100%, and 150% ambient rainfall; 1, 2.7 and 4 ºC warming above ambient in @hoeppnerInteractiveResponsesOldfield2012).
While these treatment levels may be informed by GCM model output, they often correspond to continental or global scale patterns rather than local projections, and experimental manipulations may not capture the changes in climate variability predicted by these models <!--# example and citation -->.
@owenFrameworkUsingDownscaled2019 propose a framework for using model output data from sources such as CMIP6 to obtain more precise, local predictions to use in experimental studies.
However, this approach is relatively new and has only been used in one study to our knowledge [@owenBarnyardgrassEchinochloaCrusgalli2020].

In modeling experiments and ecological forecasting...

Difficulties: <!--# should re-read Owen et al. to make sure I'm not missing anything -->

0.  Understanding CMIP models

-   box1 for vocab: "experiment", "run", "source", etc.

## CMIP terms

-   Experiment: here, an experiment refers to a run of the GCM model using a particular set of parameters.
    For example, "historical", "ssp126", and "ssp585" are each different experiments.

-   Variant: Starting conditions for model simulations are standardized across sources and indicated as "variants".
    Variant labels include indices for "r" for realization", "i" for initialization, "p" for physics, and "f" for forcing. <!--# sentence to decode variant labels or at least direct reader to documentation -->Variant "r1i1p1f1" is common to all model outputs and if your interest is in making comparisons among models, it may be helpful to restrict your search to only this variant label. If you are interested in obtaining multiple simulations, you may need to expand your search to other variant labels.

-   Source: The term "source" is used to refer to the particular model.
    For example, <!--# some example models, including two by same agency to drive home the point -->

1.  Accessing data, downloading it

Raw CMIP6 model data are hosted on four portals: esgf-node.llnl.gov (USA, PCMDI/LLNL), esgf-node.ipsl.upmc.fr (France, IPSL), esgf-data.dkrz.de (Germany, DKRZ), and esgf-index1.ceda.ac.uk (UK, CEDA).
These archives should be identical, so choose whichever portal is geographically closest to you for fastest download speeds.
Additionally, projects that summarize or aggregate CMIP6 data in various ways exist to provide data <!--# revise! -->.
The [Copernicus Climate Change Service](%5Bhttps://cds.climate.copernicus.eu%5D(https://cds.climate.copernicus.eu/#!/home)/) (CITATION), provides a portal for accessing CMIP6 data that allows filtering by time and sub-region extraction by latitude and longitude bounding box.
Additionally, they provide python code to access their API for programmatic download.
The ability to filter the global datasets combined with programmatic access can significantly speed up download times for large projects.
The World Meteorological Organization provides CMIP6 data through their [Climate Explorer](%5Bhttps://climexp.knmi.nl/%5D(https://climexp.knmi.nl/start.cgi)).
This portal provides multimodel means of 6 variables as well as individual model outputs and provides options for data filtering, subsetting, and analysis online before downloading model outputs.

-   programmatic access
-   helpful R (and python?) packages

2.  Spatial aggregation

-   not all models on same spatial scale, so may require re-gridding or downscaling
-   If you're interested in a timeseries for your region, without spatial variation, you will need to aggregate the data spatially
-   even if interested in a larger region, aggregation may be useful to simplify quality control (discussed below)

3.  Model quality control

-   Model output may contain errors, some of which may be reported and view-able through the Earth System Documentation portal at [errata.es-doc.org](https://errata.es-doc.org/static/index.html). However, not all errors may have been discovered and documented. For example, at the time of writing this manuscript we found several errors in \_\_\_\_\_ that were unreported in the system (details below).
-   even if not "errors", some models may be unrealistic for your region
-   compare observed data to "historical" experiments. Know that "historical" is not meant to be accurate to the day, but patterns like seasonality and \#of droughts should be captured accurately at a decadal scale.
-   plots to make, stats to calculate

4.  Sources of uncertainty (maybe not necessary since I don't really know what I'm talking about here yet)

-   Some researchers have used the uncertainty among CMIP models as an estimate of climate uncertainty [@duffyProjectionsFutureMeteorological2015].
-   Could also use spatial uncertainty?? (like if you aggregate a mean of a region, you can also get SD from it?)

# Acknowledgments

We thank **,** \_, \_\_\_ and \_\_\_ anonymous reviewers for helpful discussions and comments on the manuscript.
Financial support was provided by the U.S.
National Science Foundation (awards \_\_\_\_, and \_\_\_\_).
The authors delcare no conflicts of interest.

# Data Availability Statement

Data and R code used in this study are archived with Zenodo at <doi url>.

\pagebreak

# References

<!-- The following line ensures the references appear here for the MS Word or HTML output files, rather than right at the end of the document (this will not work for PDF files):  -->

::: {#refs}
:::
